### ISSUE TITLE
Reporte Práctica Librería DLL

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Yabin-2021#2]
[Rúbrica reporte de practica - DLL Calculadora.docx](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Yabin-2021/files/6362208/Rubrica.reporte.de.practica.-.DLL.Calculadora.docx)

[Reporte de Práctica - Libreria DLL.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Yabin-2021/files/6362210/Reporte.de.Practica.-.Libreria.DLL.pdf)

**Anexo rubrica de reporte de práctica y reporte de práctica**

**Comment by salathiel1999** [comment]
calificación= 17 %
califico= Irvin Barrera

**Comment by josealfredo79** [comment]
Bien hecho y revisado
